/**
 * Japanese translatese anti-pattern library — universal (IP-agnostic).
 *
 * This library provides concrete "translatese symptomology" for Japanese prose
 * generated by LLMs. When LLMs write Japanese, they tend to produce text that
 * reads like literal translations from English or Chinese: unnatural keigo
 * patterns, stiff sentence structures, wrong register choices, and
 * Chinese-influenced word order.
 *
 * Extension rules:
 * - New entries must have unique snake_case id
 * - bad / good must be real comparable Japanese paragraphs (not abstract descriptions)
 * - reason must explain WHY bad is translatese, not just say "it's unnatural"
 * - Ordered by frequency (top 5 are used in fallback scenarios)
 */

export interface JaProseStyleForbiddenPattern {
  /** snake_case unique identifier */
  id: string
  /** Bad example: Japanese with translatese */
  bad: string
  /** Good example: natural Japanese with the same meaning */
  good: string
  /** Why the bad example is translatese; identifies the source language structure */
  reason: string
}

/**
 * Universal Japanese translatese anti-pattern library.
 *
 * Current 10 entries cover the most common structural anti-patterns.
 * Top 5 (excessive_keigo / chinese_word_order / stiff_connector /
 * literal_chinese_idiom / over_explicit_subject) are used as the
 * minimum fallback subset embedded in SKILL.md templates.
 */
export const JA_TRANSLATESE_PATTERNS: JaProseStyleForbiddenPattern[] = [
  {
    id: 'excessive_keigo',
    bad: '彼女は私に対して、とても丁寧にお話しになられました。',
    good: '彼女は丁寧に話してくれた。',
    reason:
      'LLMが生成する日本語は敬語を過剰に重ねがち。「お話しになられました」は二重敬語。小説の地の文では過度な敬語は不自然。',
  },
  {
    id: 'chinese_word_order',
    bad: '彼は静かに、ゆっくりと、その古い本を開いた。',
    good: 'その古い本を、彼は静かにゆっくりと開いた。',
    reason:
      '中国語・英語のSVO語順をそのまま日本語に持ち込んでいる。日本語は目的語を先に出し、主語を省略または後置する方が自然。',
  },
  {
    id: 'stiff_connector',
    bad: 'しかしながら、それにもかかわらず、彼女は前に進み続けた。',
    good: 'それでも彼女は歩き続けた。',
    reason:
      '英語の"However, nevertheless"を直訳した冗長な接続詞の連鎖。日本語の小説文では「それでも」一語で十分。',
  },
  {
    id: 'literal_chinese_idiom',
    bad: '彼の心は石のように硬かった。',
    good: '彼は頑として動かなかった。',
    reason:
      '中国語「心硬如石」の直訳。日本語では「心が石のように硬い」とは言わない。「頑として」「意を決して」など日本語固有の表現を使う。',
  },
  {
    id: 'over_explicit_subject',
    bad: '彼女は立ち上がった。彼女は窓に歩いた。彼女は外を見た。',
    good: '立ち上がり、窓辺に歩み寄って外を見た。',
    reason:
      '英語式に毎文で主語を繰り返している。日本語は一度主語を確立したら省略し、動詞の連用形でつなぐのが自然。',
  },
  {
    id: 'passive_abuse',
    bad: 'その事実は彼によって発見された。',
    good: 'その事実に彼が気づいた。',
    reason:
      '英語の受動態"was discovered by him"の直訳。日本語は能動態を好み、受動態は被害・迷惑の意味合いで使う。発見の文脈で受動態は不自然。',
  },
  {
    id: 'unnatural_question_tag',
    bad: '美しい夜ですね、そうではありませんか？',
    good: '美しい夜ですね。',
    reason:
      '英語の付加疑問"isn\'t it?"の直訳。日本語では「ね」で十分共感を求められる。「そうではありませんか」は不自然に堅い。',
  },
  {
    id: 'emotion_over_explain',
    bad: '彼女は悲しみの感情を感じていた。その悲しみは深く、彼女の心を支配していた。',
    good: '胸の奥が、じんと痛んだ。',
    reason:
      '英語的な感情の説明的記述。「悲しみの感情を感じていた」は冗長。日本語の小説では感情を身体感覚や比喩で間接的に表現する。',
  },
  {
    id: 'clock_time_narration',
    bad: 'その時、午後3時15分だった。彼女はカフェに到着した。',
    good: '昼下がり、彼女はカフェに着いた。',
    reason:
      '英語的な時刻の正確な記述。日本語の小説では「昼下がり」「夕暮れ時」など情緒的な時間表現を好む。正確な時刻は報告的で小説的でない。',
  },
  {
    id: 'direct_thought_marker',
    bad: '「私はこれをすべきだ」と彼女は思った。「しかし、リスクが高すぎる」と彼女はまた思った。',
    good: 'やるべきだ——でも、リスクが高すぎる。',
    reason:
      '英語の"she thought"を毎回付ける直訳パターン。日本語では内面描写はダッシュや地の文で直接心理を描写し、「と思った」の繰り返しは避ける。',
  },
]
