/**
 * SKILL.md / story-spec.md template lint — author-side static checks.
 *
 * Runs inside the soulkiller process at export time. The lint cannot verify
 * what the LLM will write at runtime (script.yaml is generated by Phase 1
 * inside Claude). It only checks the static prompt text and the metadata
 * that soulkiller controls — yaml example syntax, schema-key naming,
 * cross-reference consistency between story-spec axes and SKILL.md examples.
 *
 * The packager calls these and logs the report; failures do NOT block
 * export by design (the user explicitly chose author-side review).
 */
export {
  lintSkillTemplate,
  lintStorySpec,
  lintCharacterAxesConsistency,
  lintSharedAxesInTemplate,
  type LintReport,
  type LintIssue,
} from './lint-skill-template.js'
