/**
 * Lightweight lint for SKILL.md (and optionally story-spec.md) generated by
 * `src/export/skill-template.ts` / `src/export/story-spec.ts`.
 *
 * This is **author-side lint** — it runs inside the soulkiller process at
 * export time, not on the player's machine. Its job is to catch prompt
 * authoring bugs (typos in field names, malformed yaml examples, mismatched
 * naming spaces) before a `.skill` archive is shipped.
 *
 * The lint **cannot** verify what the LLM will write at runtime (script.yaml
 * is generated by Phase 1 inside Claude, not by soulkiller). It can only
 * check the static prompt text and the metadata that soulkiller controls.
 *
 * On failure the lint emits a report; the packager logs the report but does
 * NOT block export — the user explicitly chose to "由用户确定输出的产物正常".
 */

export interface LintIssue {
  /** Human-readable rule label, e.g. "SCHEMA_KEY_NAMING". */
  rule: string
  /** Severity. Currently only `'error'` is reported. */
  severity: 'error' | 'warning'
  /** Short message describing what was wrong. */
  message: string
  /** Optional 1-based line number into the source content. */
  line?: number
  /** Optional snippet of the offending text. */
  snippet?: string
}

export interface LintReport {
  ok: boolean
  errors: LintIssue[]
  warnings: LintIssue[]
}

/** Empty starting point for the report. */
function emptyReport(): LintReport {
  return { ok: true, errors: [], warnings: [] }
}

function pushError(report: LintReport, issue: Omit<LintIssue, 'severity'>): void {
  report.errors.push({ ...issue, severity: 'error' })
  report.ok = false
}

// ── YAML fenced block extraction ─────────────────────────────────────────

interface FencedBlock {
  startLine: number   // 1-based, the ``` line
  endLine: number     // 1-based, the closing ``` line
  /** The block body (excludes the fence lines). */
  body: string
  /** The language tag after ```, e.g. "yaml" or "" if missing. */
  lang: string
}

/**
 * Find every triple-backtick fenced code block in the source. We don't care
 * about indentation — SKILL.md templates always start fences at column 0.
 */
function extractFencedBlocks(source: string): FencedBlock[] {
  const lines = source.split('\n')
  const blocks: FencedBlock[] = []
  let i = 0
  while (i < lines.length) {
    const line = lines[i]
    const open = line.match(/^```([a-zA-Z0-9_-]*)\s*$/)
    if (!open) {
      i++
      continue
    }
    const lang = open[1]
    const startLine = i + 1
    const bodyLines: string[] = []
    let j = i + 1
    while (j < lines.length && !/^```\s*$/.test(lines[j])) {
      bodyLines.push(lines[j])
      j++
    }
    if (j >= lines.length) {
      // Unterminated fence — bail out (we don't push the partial block).
      i = j + 1
      continue
    }
    blocks.push({
      startLine,
      endLine: j + 1,
      body: bodyLines.join('\n'),
      lang,
    })
    i = j + 1
  }
  return blocks
}

// ── Tolerant yaml-key extraction ─────────────────────────────────────────

/**
 * Find all top-level dictionary keys in a yaml block. We do NOT need a full
 * yaml parser — we only need to know which strings appear as `<key>:` lines
 * (with or without quotes). This is enough to verify naming rules and
 * cross-check schema/consequences references.
 *
 * Returns each match with its 1-based line number relative to the block body.
 */
function extractYamlKeys(yamlBody: string): { key: string; line: number; raw: string }[] {
  const out: { key: string; line: number; raw: string }[] = []
  const lines = yamlBody.split('\n')
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    // Match either `"<key>":` or `<key>:` at any indentation. Reject lines
    // that look like list items (`- "<x>": ...`) since those carry value
    // pairs not field declarations.
    const m = line.match(/^(\s*)("?)([A-Za-z_][\w.<>?-]*)\2\s*:/)
    if (!m) continue
    const key = m[3]
    out.push({ key, line: i + 1, raw: line })
  }
  return out
}

// ── Schema-key naming check ──────────────────────────────────────────────

/**
 * Validate a schema key according to the design rules:
 *  - ASCII only
 *  - snake_case (lowercase, digits, underscores)
 *  - dot-separated namespace
 *  - must be a literal string (the caller already verifies it was quoted)
 *
 * Returns null if OK, otherwise an error message.
 *
 * Allowed pattern: `[a-z][a-z0-9_]*` segments separated by dots.
 * Placeholder forms like `<character>` and `<axis>` are tolerated inside
 * angle brackets so example keys in the prompt template don't trip the lint.
 */
function validateSchemaKey(key: string): string | null {
  if (!/^[\x20-\x7e]+$/.test(key)) return 'non-ASCII characters in schema key'
  // Allow placeholder syntax `<...>` for example/template keys.
  // Remove placeholder segments before structural validation.
  const stripped = key.replace(/<[^>]+>/g, '<placeholder>')
  // Valid segment: snake_case OR kebab-case (slug from formatPathSegment)
  // OR angle-bracket placeholder. Slugs can contain hyphens but must start
  // with [a-z], end with [a-z0-9], and not have consecutive hyphens.
  // The character set [a-z0-9_-] covers both snake and kebab cases; the
  // anchor + tail rules block leading/trailing hyphens.
  const segmentPattern = /^([a-z][a-z0-9_-]*[a-z0-9]|[a-z]|<placeholder>)$/
  const segments = stripped.split('.')
  if (segments.length === 0) return 'empty key'
  for (const seg of segments) {
    if (!segmentPattern.test(seg)) {
      return `invalid segment "${seg}" — schema keys must be snake_case / kebab-case ASCII slug or angle-bracket placeholder`
    }
    // Reject consecutive hyphens within a segment.
    if (/--/.test(seg)) {
      return `invalid segment "${seg}" — consecutive hyphens not allowed`
    }
  }
  return null
}

// ── Lint pass 1: yaml example parses (tolerant) ─────────────────────────

/**
 * Each yaml-tagged fenced block in the SKILL.md template should be at least
 * roughly parseable. We do not require strict yaml — only that:
 *   1. lines that look like `key: value` have a non-empty key
 *   2. there are no obviously broken constructs like trailing colon with
 *      content on the same indent level
 *
 * Tolerant by design: real yaml may use list items, multi-line scalars,
 * and angle-bracket placeholders. We only flag the most egregious cases.
 */
function lintYamlBlock(block: FencedBlock, report: LintReport): void {
  if (block.lang !== 'yaml') return
  const lines = block.body.split('\n')
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    // Empty colon: `key:` is fine (block scalar follows). But `: value`
    // with no key is a hard error.
    if (/^\s*:\s*\S/.test(line)) {
      pushError(report, {
        rule: 'YAML_PARSE',
        message: 'value without key in yaml example',
        line: block.startLine + i,
        snippet: line,
      })
    }
  }
}

// ── Lint pass 2: schema keys naming ─────────────────────────────────────

/**
 * Walk every yaml block looking for the `state_schema:` section. Within it,
 * collect all child keys and run them through `validateSchemaKey`.
 *
 * Heuristic: a yaml block contains state_schema if any line at the leftmost
 * indent is `state_schema:`. Within that section, the next indentation level
 * lines are the schema field keys. We stop tracking when indentation drops
 * back to 0.
 */
function lintSchemaKeyNaming(block: FencedBlock, report: LintReport): void {
  if (block.lang !== 'yaml') return
  const lines = block.body.split('\n')
  let inSchema = false
  let schemaIndent = -1
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    if (/^state_schema\s*:\s*$/.test(line.trim()) && !inSchema) {
      inSchema = true
      schemaIndent = line.search(/\S/)
      continue
    }
    if (!inSchema) continue
    // Empty line — keep going.
    if (/^\s*$/.test(line)) continue
    const indent = line.search(/\S/)
    // Drop back to root → leave schema scope.
    if (indent <= schemaIndent) {
      inSchema = false
      continue
    }
    // Look for schema field declarations: a quoted key at exactly one level
    // deeper than schema_indent.
    const fieldMatch = line.match(/^(\s+)"([^"]+)"\s*:/)
    if (!fieldMatch) continue
    const fieldIndent = fieldMatch[1].length
    // We only check direct children of state_schema (one indent level deeper).
    if (fieldIndent !== schemaIndent + 2) continue
    const key = fieldMatch[2]
    const err = validateSchemaKey(key)
    if (err) {
      pushError(report, {
        rule: 'SCHEMA_KEY_NAMING',
        message: `${err}: "${key}"`,
        line: block.startLine + i,
        snippet: line,
      })
    }
  }
}

// ── Lint pass 3: placeholder format consistency ─────────────────────────

/**
 * Check that placeholders in the prompt body use a single style:
 *  - `<placeholder>` is the canonical form
 *  - `{placeholder}` is also accepted (markdown variable convention)
 *
 * We flag mixed usage in the same single-character template. The rule is
 * lenient — we only complain when both styles appear inside the same yaml
 * code block, which usually indicates a copy-paste mistake.
 */
function lintPlaceholderFormat(block: FencedBlock, report: LintReport): void {
  if (block.lang !== 'yaml') return
  const hasAngle = /<[A-Za-z_][^<>]*>/.test(block.body)
  const hasBrace = /\{[A-Za-z_][^{}]*\}/.test(block.body)
  // Tolerate both styles inside the same block — many prompts mix them
  // intentionally (e.g. `{{soul.name}}` for templates and `<id>` for values).
  // Only flag if BOTH are used AND we see clear angle-style key declarations.
  // Disabled for v1 — kept here as a structural placeholder for future
  // strictness if mixed styles cause confusion in practice.
  void hasAngle
  void hasBrace
}

// ── Public API ──────────────────────────────────────────────────────────

/**
 * Lint a SKILL.md template content. Returns a report — caller decides
 * whether to abort export or just log the warnings.
 */
export function lintSkillTemplate(skillContent: string): LintReport {
  const report = lintFencedBlocksOnly(skillContent)
  // Runtime CLI usage rules apply ONLY to SKILL.md, not to story-spec.md.
  // story-spec.md is metadata for the author workflow and doesn't need to
  // reference the runtime state CLI at all.
  lintRuntimeCliUsage(skillContent, report)
  return report
}

/**
 * Run only the fenced-block checks (yaml syntax, schema naming, placeholder
 * format, shared axes completeness). Used by both `lintSkillTemplate` and
 * `lintStorySpec` so that runtime CLI checks stay SKILL.md-only.
 */
function lintFencedBlocksOnly(content: string): LintReport {
  const report = emptyReport()
  const blocks = extractFencedBlocks(content)
  for (const block of blocks) {
    lintYamlBlock(block, report)
    lintSchemaKeyNaming(block, report)
    lintPlaceholderFormat(block, report)
    lintSharedAxesCompleteness(block, report)
  }
  return report
}

/**
 * Verify the skill template consistently routes state management through
 * the `soulkiller runtime` CLI instead of having the LLM do it manually.
 *
 * Three scan-level rules:
 *   - PHASE_MINUS_ONE_INSTALL_GUIDE_PRESENT — Phase -1 must provide a
 *     command-not-found → AskUserQuestion install guide branch
 *   - STATE_APPLY_PRESENT — Phase 2 must reference `soulkiller runtime apply`
 *   - NO_EDIT_STATE_YAML  — no literal "Edit state.yaml" / "Edit meta.yaml"
 *                           instructions anywhere in the template
 *
 * These are the structural guarantees that make Group 4's SKILL.md rewrite
 * robust to accidental regressions in future template edits.
 */
function lintRuntimeCliUsage(skillContent: string, report: LintReport): void {
  // PHASE_MINUS_ONE_INSTALL_GUIDE_PRESENT — Phase -1 must surface a
  // command-not-found → install-guide branch so the LLM knows what to do
  // when `soulkiller runtime <subcommand>` is unavailable. We require all
  // four literal anchors to appear anywhere in SKILL.md. Missing any means
  // the install-recovery branch is incomplete and users without soulkiller
  // installed would be stuck.
  const installGuideMarkers = [
    'command not found',
    'AskUserQuestion',
    'install.sh',
    'install.ps1',
  ]
  const missingMarkers = installGuideMarkers.filter((m) => !skillContent.includes(m))
  if (missingMarkers.length > 0) {
    pushError(report, {
      rule: 'PHASE_MINUS_ONE_INSTALL_GUIDE_PRESENT',
      message:
        'Phase -1 安装引导分支不完整 — SKILL.md 必须在 Phase -1 里保留完整的 ' +
        'command-not-found → AskUserQuestion 安装引导（含 macOS/Linux 的 install.sh ' +
        `和 Windows 的 install.ps1 两条命令）。缺失: ${missingMarkers.join(', ')}`,
    })
  }

  // STATE_APPLY_PRESENT — Phase 2 场景流转必须调 state apply
  const applyMarker = 'soulkiller runtime apply'
  if (!skillContent.includes(applyMarker)) {
    pushError(report, {
      rule: 'STATE_APPLY_PRESENT',
      message:
        'Phase 2 场景流转缺失 CLI 调用 — SKILL.md 必须至少出现一次 ' +
        `"${applyMarker}" 调用。未找到意味着 LLM 可能退回到手动 Edit state.yaml。`,
    })
  }

  // NO_EDIT_STATE_YAML — scan for forbidden literal strings that would
  // instruct the LLM to modify state.yaml / meta.yaml directly.
  // We match on the literal substring because that's what Phase 2's pseudo-
  // code used to contain. Match is case-sensitive and space-insensitive around
  // the target path segment.
  const forbiddenPatterns: { pattern: RegExp; snippet: string }[] = [
    { pattern: /Edit\s+\$\{CLAUDE_SKILL_DIR\}\/runtime\/saves\/[^\s]*state\.yaml/i, snippet: 'Edit ${CLAUDE_SKILL_DIR}/runtime/saves/.../state.yaml' },
    { pattern: /Edit\s+\$\{CLAUDE_SKILL_DIR\}\/runtime\/saves\/[^\s]*meta\.yaml/i, snippet: 'Edit ${CLAUDE_SKILL_DIR}/runtime/saves/.../meta.yaml' },
    // The old pseudo-code lines that still started with plain `Edit state.yaml:`
    { pattern: /(^|\s)Edit\s+state\.yaml:/m, snippet: 'Edit state.yaml:' },
    { pattern: /(^|\s)Edit\s+meta\.yaml:/m, snippet: 'Edit meta.yaml:' },
  ]
  for (const { pattern, snippet } of forbiddenPatterns) {
    const match = pattern.exec(skillContent)
    if (match) {
      // Locate the line number by counting newlines up to match.index
      const line = skillContent.slice(0, match.index).split('\n').length
      pushError(report, {
        rule: 'NO_EDIT_STATE_YAML',
        message:
          'SKILL.md 禁止出现直接 Edit state.yaml / meta.yaml 的指令 — ' +
          '所有状态写入必须通过 soulkiller runtime {init,apply,reset,rebuild}',
        line,
        snippet,
      })
    }
  }
}

/**
 * Lint a story-spec.md template content. Shares the fenced-block rules with
 * SKILL.md (yaml syntax, schema naming, shared-axes completeness) but
 * **skips** runtime CLI checks — story-spec.md is author metadata and has
 * no reason to reference the state CLI.
 */
export function lintStorySpec(storySpecContent: string): LintReport {
  return lintFencedBlocksOnly(storySpecContent)
}

/**
 * Cross-spec consistency: verify that every CharacterSpec.axes name appears
 * in at least one `affinity.<character>.<axis>` style schema example inside
 * the SKILL.md template.
 *
 * This catches the common bug "we renamed an axis in story-spec but forgot
 * to update the SKILL.md schema example."
 */
export function lintCharacterAxesConsistency(
  skillContent: string,
  storySpecContent: string,
): LintReport {
  const report = emptyReport()
  // Extract `<axis>: <number>` lines from story-spec.md (axes appear inside
  // `[...]` blocks like `axes: - { name: "...", english: trust, ... }`).
  // We use a tolerant regex on `english:` since that's the schema key root.
  const axisRegex = /english:\s*([a-z][a-z0-9_]*)/g
  const declared = new Set<string>()
  let m: RegExpExecArray | null
  while ((m = axisRegex.exec(storySpecContent)) !== null) {
    declared.add(m[1])
  }

  // Look for any string ending in `.<axis>"` inside BOTH the SKILL.md
  // template AND the story-spec.md template — story-spec is where the
  // packager renders per-character schema examples using the actual cast,
  // while SKILL.md examples are generic teaching aids. Either side counts
  // as "the axis is referenced somewhere the LLM will see at runtime".
  const used = new Set<string>()
  // Character segment may be either snake_case (legacy) or kebab-case slug
  // (`skill-abc12345`, `char-xxx`); axis segment is always snake_case.
  const usageRegex = /"affinity\.[a-z][a-z0-9_-]*[a-z0-9]\.([a-z][a-z0-9_]*)"/g
  for (const haystack of [skillContent, storySpecContent]) {
    // Reset lastIndex on each pass since the regex has the /g flag.
    usageRegex.lastIndex = 0
    while ((m = usageRegex.exec(haystack)) !== null) {
      used.add(m[1])
    }
  }

  // Report any declared axis that the template never references.
  // Note: declared.size === 0 is fine — it just means no characters were
  // configured (the template falls back to single-character mode).
  if (declared.size > 0 && used.size > 0) {
    for (const axis of declared) {
      if (!used.has(axis)) {
        pushError(report, {
          rule: 'AXIS_CROSS_REF',
          message: `axis "${axis}" declared in story-spec.md is not referenced in any SKILL.md schema example`,
        })
      }
    }
  }

  return report
}

// ── SHARED_AXES_COMPLETENESS ────────────────────────────────────────────

/**
 * Verify each character present in a state_schema yaml example has the full
 * set of shared axes: `bond` + 2 story-defined shared axes, and that the two
 * non-bond shared axes are **the same set** across every character in that
 * example.
 */
function lintSharedAxesCompleteness(block: FencedBlock, report: LintReport): void {
  if (block.lang !== 'yaml') return
  // Only apply this rule to blocks that are actual state_schema declarations.
  // Ending condition examples (`{ key: "affinity.x.y", op: ">=", value: 5 }`)
  // reference affinity keys but do not need to declare the full shared set —
  // that check lives in the state_schema block itself.
  const lines = block.body.split('\n')
  const hasStateSchemaHeader = lines.some((l) => /^\s*state_schema\s*:\s*$/.test(l))
  if (!hasStateSchemaHeader) return
  const perChar: Map<string, Set<string>> = new Map()
  // Only count lines where the affinity key is a dictionary declaration
  // (i.e. `"affinity.x.y":` followed by end of line or whitespace, at the
  // start of the line after any indent). Usage inside comparison nodes is
  // excluded because it is not a schema declaration.
  const declRegex = /^\s*"affinity\.([a-z][a-z0-9_-]*[a-z0-9]|[a-z])\.([a-z][a-z0-9_]*)"\s*:/
  for (const line of lines) {
    const m = line.match(declRegex)
    if (!m) continue
    const char = m[1]
    const axis = m[2]
    if (!perChar.has(char)) perChar.set(char, new Set())
    perChar.get(char)!.add(axis)
  }
  // Need at least 2 characters to check cross-character shared structure.
  if (perChar.size < 2) return

  // Bond is platform-fixed: every character must have it.
  let anyMissingBond = false
  for (const [char, axes] of perChar.entries()) {
    if (!axes.has('bond')) {
      anyMissingBond = true
      pushError(report, {
        rule: 'SHARED_AXES_COMPLETENESS',
        message: `character "${char}" missing shared axis "bond" in state_schema example`,
        line: block.startLine,
      })
    }
  }
  if (anyMissingBond) return

  // Compute intersection — the axes every character shares.
  let intersection: Set<string> | null = null
  for (const axes of perChar.values()) {
    if (intersection === null) {
      intersection = new Set(axes)
    } else {
      for (const a of [...intersection]) {
        if (!axes.has(a)) intersection.delete(a)
      }
    }
  }
  if (!intersection) return

  const nonBondShared = [...intersection].filter((a) => a !== 'bond')
  if (nonBondShared.length < 2) {
    // Find a character missing one of the shared axes to give a helpful example.
    const allSeenAxes = new Set<string>()
    for (const axes of perChar.values()) for (const a of axes) allSeenAxes.add(a)
    const candidateShared = [...allSeenAxes].filter((a) => a !== 'bond')
    for (const axis of candidateShared) {
      for (const [char, axes] of perChar.entries()) {
        if (!axes.has(axis)) {
          // Only report if at least one *other* character has this axis,
          // suggesting it was intended to be shared.
          const othersHave = [...perChar.values()].some((s) => s.has(axis))
          if (othersHave) {
            pushError(report, {
              rule: 'SHARED_AXES_COMPLETENESS',
              message: `character "${char}" missing shared axis "${axis}" (present on other characters in the same state_schema example)`,
              line: block.startLine,
            })
          }
        }
      }
    }
  }
}

/**
 * Public wrapper: run SHARED_AXES_COMPLETENESS across every yaml block in a
 * SKILL.md template.
 */
/**
 * Verify the archive's `soulkiller.json` carries a meaningful author-declared
 * version (skill-author-version change). Warns on:
 *   - missing `version` field
 *   - `version === "0.0.0"` (reserved for legacy archives whose version was
 *     back-filled by the upgrade script — new exports should start at 0.1.0+)
 *
 * Warnings never block export; the author sees them in stderr and can decide
 * whether to re-export with an intentional value.
 */
export function lintAuthorVersion(soulkillerJsonContent: string): LintReport {
  const report: LintReport = emptyReport()
  let parsed: Record<string, unknown>
  try {
    parsed = JSON.parse(soulkillerJsonContent) as Record<string, unknown>
  } catch {
    report.warnings.push({
      severity: 'warning',
      rule: 'AUTHOR_VERSION_PRESENT',
      message: `soulkiller.json is malformed; cannot check author version`,
    })
    return report
  }
  const version = parsed.version
  if (typeof version !== 'string' || version.length === 0) {
    report.warnings.push({
      severity: 'warning',
      rule: 'AUTHOR_VERSION_PRESENT',
      message: `soulkiller.json lacks 'version' field — author version is required for catalog diff to work. Re-export via /export to set it.`,
    })
    return report
  }
  if (version === '0.0.0') {
    report.warnings.push({
      severity: 'warning',
      rule: 'AUTHOR_VERSION_PRESENT',
      message: `soulkiller.json 'version' is "0.0.0" — reserved for legacy archives whose version was back-filled. New exports should start at 0.1.0+.`,
    })
  }
  return report
}

export function lintSharedAxesInTemplate(skillContent: string): LintReport {
  const report = emptyReport()
  const blocks = extractFencedBlocks(skillContent)
  for (const block of blocks) {
    lintSharedAxesCompleteness(block, report)
  }
  return report
}
