import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import { fileURLToPath } from 'node:url'
import { zipSync, strToU8, type ZipOptions } from 'fflate'
import { readManifest, readSoulFiles } from '../soul/package.js'
import { loadWorld, getWorldDir } from '../world/manifest.js'
import { generateSkillMd } from './skill-template.js'
import { generateStorySpec, type StorySpecConfig } from './story-spec.js'
import {
  lintSkillTemplate,
  lintStorySpec,
  lintCharacterAxesConsistency,
  type LintReport,
} from './lint/index.js'
import {
  formatSkillBaseName,
  formatPathSegment,
  isValidSkillName,
} from './format/index.js'

export interface PackageConfig {
  /** Array of soul names to include in souls/<name>/ subdirectories */
  souls: string[]
  world_name: string
  /** Story name provided by the user — used as the skill identity (file name + description) */
  story_name: string
  story_spec: StorySpecConfig
  /** Required absolute path of the parent directory where the .skill file will be created */
  output_base_dir: string
}

export interface PackageResult {
  /** Absolute path to the generated .skill archive file */
  output_file: string
  /** Number of files inside the archive */
  file_count: number
  /** Size of the .skill file in bytes */
  size_bytes: number
}

/**
 * Compute the base name (no extension) for a skill, derived from story name + world.
 * Result is a strict ASCII slug compliant with the Anthropic Skill spec
 * (`^[a-z0-9]+(-[a-z0-9]+)*$`, 1–64 chars). The formatter falls back to a
 * deterministic hash slug when the input is pure CJK so that `远坂凛-的故事`
 * produces a stable, valid name without forcing the user to provide an
 * English alternative.
 *
 * Example: `("FSN伊莉雅线", "Fate Stay Night")` → `"fsn-in-fate-stay-night"`
 * Example: `("远坂凛的故事", "命运长夜")` → `"skill-<hash>-in-skill-<hash>"`
 */
export function getSkillBaseName(storyName: string, worldName: string): string {
  return formatSkillBaseName(storyName, worldName)
}

/**
 * Compute the full skill archive file name (with .skill extension).
 */
export function getSkillFileName(storyName: string, worldName: string): string {
  return `${getSkillBaseName(storyName, worldName)}.skill`
}

interface SoulArchiveEntry {
  /** ASCII slug used as the souls/<slug>/ directory name. */
  slug: string
  /** Original (possibly CJK) soul name — preserved for display in SKILL.md. */
  originalName: string
  /** Map of archive paths (already prefixed with `souls/<slug>/`) → file bytes. */
  files: Record<string, Uint8Array>
  /** Soul display name from manifest, or originalName as fallback. */
  displayName: string
}

/**
 * Build the in-memory file map for one soul, namespaced under
 * `souls/<slug>/`. The slug is generated by the formatter so the path is
 * guaranteed ASCII even when the soul directory name is CJK.
 *
 * The original soul name is preserved on the returned record so callers can
 * surface a path-mapping table inside SKILL.md (LLM needs to know that
 * `远坂凛` lives at `souls/skill-abc12345/`).
 */
function buildSoulFiles(soulName: string): SoulArchiveEntry {
  const soulDir = path.join(os.homedir(), '.soulkiller', 'souls', soulName)
  const manifest = readManifest(soulDir)
  const soulFiles = readSoulFiles(soulDir)
  const slug = formatPathSegment(soulName, 'soul')

  const files: Record<string, Uint8Array> = {}
  files[`souls/${slug}/identity.md`] = strToU8(soulFiles.identity)
  files[`souls/${slug}/style.md`] = strToU8(soulFiles.style)
  if (soulFiles.capabilities) {
    files[`souls/${slug}/capabilities.md`] = strToU8(soulFiles.capabilities)
  }
  if (soulFiles.milestones) {
    files[`souls/${slug}/milestones.md`] = strToU8(soulFiles.milestones)
  }

  // Read behavior files
  const srcBehaviorsDir = path.join(soulDir, 'soul', 'behaviors')
  if (fs.existsSync(srcBehaviorsDir)) {
    const behaviorFiles = fs.readdirSync(srcBehaviorsDir).filter((f) => f.endsWith('.md')).sort()
    for (const f of behaviorFiles) {
      const content = fs.readFileSync(path.join(srcBehaviorsDir, f))
      files[`souls/${slug}/behaviors/${f}`] = new Uint8Array(content)
    }
  }

  return {
    slug,
    originalName: soulName,
    files,
    displayName: manifest?.display_name ?? soulName,
  }
}

export function packageSkill(config: PackageConfig): PackageResult {
  const { souls, world_name, story_name, story_spec, output_base_dir } = config

  if (!souls || souls.length === 0) {
    throw new Error('packageSkill requires at least one soul')
  }
  if (!story_name || story_name.trim().length === 0) {
    throw new Error('packageSkill requires a non-empty story_name')
  }
  if (!output_base_dir) {
    throw new Error('packageSkill requires output_base_dir')
  }

  // The base name doubles as the SKILL.md frontmatter `name` field and the
  // archive's top-level directory. The formatter guarantees ASCII compliance.
  const baseName = getSkillBaseName(story_name, world_name)
  // Defensive sanity check — if formatter ever produces a non-compliant
  // string this should fail loud rather than ship a broken skill.
  if (!isValidSkillName(baseName)) {
    throw new Error(
      `Internal: formatSkillBaseName produced non-compliant slug "${baseName}". ` +
        `This is a packager bug.`,
    )
  }
  const fileName = `${baseName}.skill`
  const outputFile = path.join(output_base_dir, fileName)

  // Ensure parent dir exists (three preset output locations may not exist yet)
  fs.mkdirSync(output_base_dir, { recursive: true })

  // Remove existing archive if any (overwrite semantics)
  if (fs.existsSync(outputFile)) {
    fs.rmSync(outputFile)
  }

  // ── Build the in-memory file map ─────────────────────────────────
  //
  // Spec compliance: every archive entry is nested inside `<baseName>/` so
  // the unzipped layout matches the personal-skill install path
  // `~/.claude/skills/<name>/SKILL.md` that Anthropic expects.
  //
  // We build the file map with **unprefixed** paths (e.g. `souls/<slug>/...`)
  // and then prefix them all in one pass at the end. This keeps every
  // upstream block (souls, world, skill md, runtime) free of the prefix
  // detail and makes it impossible to forget the prefix on a new file type.

  const unprefixedFiles: Record<string, Uint8Array> = {}

  // 1. Souls — collect each soul into souls/<slug>/
  // Track the original-name → slug mapping so SKILL.md can render a path
  // table for the LLM (it needs to know that `远坂凛` lives at
  // `souls/skill-abc12345/` to read identity/style/etc).
  const soulSlugByName = new Map<string, string>()
  for (const soulName of souls) {
    const entry = buildSoulFiles(soulName)
    soulSlugByName.set(entry.originalName, entry.slug)
    Object.assign(unprefixedFiles, entry.files)
  }

  // Enrich story_spec.characters with display_name from manifest if missing
  if (story_spec.characters) {
    for (const char of story_spec.characters) {
      if (!char.display_name) {
        const soulDir = path.join(os.homedir(), '.soulkiller', 'souls', char.name)
        const manifest = readManifest(soulDir)
        if (manifest) char.display_name = manifest.display_name
      }
    }
  }

  // 2. World files — world/world.json + world/<dimension>/*.md (per-dimension layout)
  const worldDir = getWorldDir(world_name)
  const worldJsonSrc = path.join(worldDir, 'world.json')
  if (fs.existsSync(worldJsonSrc)) {
    unprefixedFiles['world/world.json'] = new Uint8Array(fs.readFileSync(worldJsonSrc))
  }

  // Dimension subdirectories — each one is a flat list of regular entries.
  // Skip `_*.md` (author views like _index.md) and the history-specific
  // subfiles (timeline.md + events/) which are copied below.
  const DIMENSIONS = ['geography', 'history', 'factions', 'systems', 'society', 'culture', 'species', 'figures', 'atmosphere'] as const
  for (const dim of DIMENSIONS) {
    const dimDir = path.join(worldDir, dim)
    if (!fs.existsSync(dimDir)) continue
    for (const f of fs.readdirSync(dimDir)) {
      if (!f.endsWith('.md')) continue
      if (f.startsWith('_')) continue
      if (dim === 'history' && f === 'timeline.md') continue
      const full = path.join(dimDir, f)
      try {
        if (!fs.statSync(full).isFile()) continue
      } catch {
        continue
      }
      unprefixedFiles[`world/${dim}/${f}`] = new Uint8Array(fs.readFileSync(full))
    }
  }

  // 2.5 World chronicle — timeline single file + events directory under history/.
  // Optional: worlds without a history subtree are simply skipped.
  const timelineSrc = path.join(worldDir, 'history', 'timeline.md')
  if (fs.existsSync(timelineSrc)) {
    unprefixedFiles['world/history/timeline.md'] = new Uint8Array(fs.readFileSync(timelineSrc))
  }
  const eventsDir = path.join(worldDir, 'history', 'events')
  if (fs.existsSync(eventsDir)) {
    for (const f of fs.readdirSync(eventsDir)) {
      if (!f.endsWith('.md')) continue
      if (f.startsWith('_')) continue
      unprefixedFiles[`world/history/events/${f}`] = new Uint8Array(
        fs.readFileSync(path.join(eventsDir, f)),
      )
    }
  }

  // 3. story-spec.md
  const storySpecContent = generateStorySpec(story_spec)
  unprefixedFiles['story-spec.md'] = strToU8(storySpecContent)

  // 4. SKILL.md (skillName uses baseName WITHOUT .skill extension)
  const worldManifest = loadWorld(world_name)
  const worldDisplayName = worldManifest?.display_name ?? world_name
  const isMulti = souls.length > 1

  const description = isMulti
    ? `${story_name} — 在${worldDisplayName}中的多角色视觉小说。每次运行都是全新剧本。`
    : `${story_name} — 在${worldDisplayName}中的视觉小说。每次运行都是全新故事。`

  // Build a CharacterSpec[] augmented with slugs so skill-template can
  // generate paths and the path-mapping table from a single source. We
  // mutate the input characters in-place because they're plain interfaces
  // and downstream consumers don't care about the extra `slug` field.
  const charactersWithSlugs = (story_spec.characters ?? []).map((c) => ({
    ...c,
    slug: soulSlugByName.get(c.name) ?? formatPathSegment(c.name, 'soul'),
  }))

  // Phase 1 full-read enforcement: compute file count and text size from the
  // in-memory map so we can inject concrete budget numbers into the SKILL.md
  // Phase 1 prompt. This is the anchor that tells the LLM "you need ~N files
  // / ~M KB, you have 1M context, don't default to partial Read".
  //
  // Count: every md file that the LLM will actually Read at runtime,
  // covering souls/, world/, and story-spec.md. world/world.json is
  // excluded (binary metadata, not a prose file Phase 1 reads).
  const expectedFileCount = countMdFilesInMap(unprefixedFiles)
  const expectedTextSizeKb = estimateMdTextSizeKb(unprefixedFiles)

  const skillContent = generateSkillMd({
    skillName: baseName,
    storyName: story_name,
    worldDisplayName: worldDisplayName,
    description,
    characters: charactersWithSlugs,
    acts_options: story_spec.acts_options,
    default_acts: story_spec.default_acts,
    expectedFileCount,
    expectedTextSizeKb,
  })
  unprefixedFiles['SKILL.md'] = strToU8(skillContent)

  // 4.5 Author-side template lint — runs in the soulkiller process, never on
  //     the player's machine. The lint catches static prompt bugs (yaml
  //     example syntax, schema-key naming, axis cross-references) before the
  //     archive is shipped. Failures are logged to stderr but do NOT block
  //     export — by user choice, the author audits the report manually.
  //     Note: spec-compliance violations (frontmatter `name`, allowed-tools
  //     format, archive paths) are handled by the formatter at write time,
  //     not by lint, so they will not appear in this report.
  const reports: { source: string; report: LintReport }[] = [
    { source: 'SKILL.md', report: lintSkillTemplate(skillContent) },
    { source: 'story-spec.md', report: lintStorySpec(storySpecContent) },
    { source: 'cross-ref', report: lintCharacterAxesConsistency(skillContent, storySpecContent) },
  ]
  reportLintIssues(reports)

  // 5. Runtime placeholder directories — scripts/ and saves/ are populated
  //    at skill runtime when LLM persists generated scripts and player saves.
  //    .gitkeep files reserve the directory inside the zip archive.
  unprefixedFiles['runtime/scripts/.gitkeep'] = strToU8('')
  unprefixedFiles['runtime/saves/.gitkeep'] = strToU8('')

  // 5.5 Runtime code — inject doctor.sh + state wrapper (bash) + bun .ts libs
  //     from src/export/state/. These are the same files Soulkiller unit-tests
  //     against, copied byte-for-byte into the archive. bash/sh entry points
  //     are marked executable (0755) via fflate attrs; .ts files stay 0644.
  const execPaths = injectRuntimeFiles(unprefixedFiles)

  // ── Apply top-level directory prefix ─────────────────────────────
  //
  // Anthropic Skill spec requires the archive to contain a single top-level
  // directory matching the `name` field. We prefix every collected path
  // with `<baseName>/` here, in one place, so it's impossible to ship a
  // skill that violates the layout requirement.
  //
  // We also defensively check every final path for ASCII compliance — if
  // a non-ASCII path slipped through (e.g. soul name slug formatter
  // regression), this would catch it before zip write.
  const archiveFiles: Record<string, Uint8Array | [Uint8Array, ZipOptions]> = {}
  const nonAsciiPaths: string[] = []
  for (const [key, value] of Object.entries(unprefixedFiles)) {
    const finalPath = `${baseName}/${key}`
    // Anthropic spec doesn't explicitly forbid non-ASCII archive paths, but
    // empirically the upload validator rejects them. The formatter is
    // supposed to keep everything ASCII; if a non-ASCII path made it this
    // far it means a code path skipped the formatter, which is a bug.
    if (!/^[\x00-\x7f]+$/.test(finalPath)) {
      nonAsciiPaths.push(finalPath)
    }
    // Runtime bash/sh entry points need exec bit preserved inside the zip.
    // fflate attrs format: upper 16 bits = Unix mode, os must be 3 (Unix).
    archiveFiles[finalPath] = execPaths.has(key)
      ? [value, { os: 3, attrs: (0o100755 << 16) >>> 0 }]
      : value
  }
  if (nonAsciiPaths.length > 0) {
    throw new Error(
      `Internal: ${nonAsciiPaths.length} archive path(s) contain non-ASCII characters. ` +
        `This violates Anthropic Skill spec and is a packager bug. ` +
        `Offending paths: ${nonAsciiPaths.slice(0, 5).join(', ')}${nonAsciiPaths.length > 5 ? ', ...' : ''}`,
    )
  }

  // ── Zip and write ─────────────────────────────────

  const zipped = zipSync(archiveFiles)
  fs.writeFileSync(outputFile, zipped)

  return {
    output_file: outputFile,
    file_count: Object.keys(archiveFiles).length,
    size_bytes: zipped.length,
  }
}

/**
 * Print lint reports to stderr in a compact human-readable form. Never
 * throws — lint failure is informational, not blocking. Each issue is
 * prefixed with the source file name and (when present) line number, so
 * authors can scan multiple reports at once.
 */
function reportLintIssues(reports: { source: string; report: LintReport }[]): void {
  let totalErrors = 0
  for (const { source, report } of reports) {
    if (report.errors.length === 0) continue
    totalErrors += report.errors.length
    process.stderr.write(`\n[lint] ${source}: ${report.errors.length} error(s)\n`)
    for (const issue of report.errors) {
      const loc = issue.line !== undefined ? `:${issue.line}` : ''
      process.stderr.write(`  [${issue.rule}] ${source}${loc} — ${issue.message}\n`)
      if (issue.snippet) {
        process.stderr.write(`    > ${issue.snippet.trim()}\n`)
      }
    }
  }
  if (totalErrors > 0) {
    process.stderr.write(
      `\n[lint] export 完成但发现 ${totalErrors} 个模板问题。归档已写出，请审核报告并视情况修正后重新 export。\n`,
    )
  }
}

// ── Phase 1 full-read enforcement helpers ────────────────────────────────

/**
 * Count every md file in the in-memory archive map that the Phase 1 LLM
 * is expected to Read at runtime. Includes soul md files (identity, style,
 * capabilities, milestones, behaviors), world dimension md files, history
 * chronicle md files, and story-spec.md. Binary metadata like world.json
 * is excluded.
 *
 * Exported for tests; used internally by packageSkill to inject the count
 * into the Phase 1 context-budget declaration in SKILL.md.
 */
export function countMdFilesInMap(files: Record<string, Uint8Array>): number {
  let count = 0
  for (const key of Object.keys(files)) {
    // Runtime code files are excluded — they're not Phase 1 creative source
    // material. Guard kept explicit even though the .md filter would catch
    // .sh/.ts today, so future runtime .md additions (e.g. a README) don't
    // silently inflate the budget.
    if (key.startsWith('runtime/')) continue
    if (key.endsWith('.md')) count += 1
  }
  return count
}

/**
 * Estimate the total text size (in kilobytes, rounded to the nearest int)
 * of every md file in the archive map. Used as the Phase 1 budget anchor
 * so the LLM knows "this is ~M KB, well under your 1M context window,
 * don't default to partial reads".
 *
 * Uses byte length (not character count) since that's what matters for
 * tokenizer-agnostic budget estimation. Divides by 1024 with rounding.
 */
export function estimateMdTextSizeKb(files: Record<string, Uint8Array>): number {
  let totalBytes = 0
  for (const [key, bytes] of Object.entries(files)) {
    // Exclude runtime code for the same reason as countMdFilesInMap.
    if (key.startsWith('runtime/')) continue
    if (key.endsWith('.md')) totalBytes += bytes.length
  }
  return Math.max(1, Math.round(totalBytes / 1024))
}

/**
 * Inject skill runtime files (doctor.sh, state wrapper, bun .ts lib) from
 * `src/export/state/` into the in-memory archive map. These are the same
 * files Soulkiller's vitest suite exercises, copied byte-for-byte so that
 * the consumer-side runtime is guaranteed to match what unit tests cover.
 *
 * File placement inside the archive:
 *   src/export/state/doctor.sh  → runtime/bin/doctor.sh     (executable)
 *   src/export/state/state.sh   → runtime/bin/state          (executable, .sh stripped)
 *   src/export/state/*.ts       → runtime/lib/<name>.ts      (regular)
 *
 * Returns the set of unprefixed archive paths that require the executable
 * bit. Callers use this to apply fflate ZipOptions attrs at the final zip
 * step.
 *
 * Exported for tests.
 */
export function injectRuntimeFiles(files: Record<string, Uint8Array>): Set<string> {
  const stateSrcDir = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    'state'
  )
  const execPaths = new Set<string>()

  // doctor.sh — POSIX health check, keeps .sh extension so it's clear this
  // is the one file that stays raw shell.
  files['runtime/bin/doctor.sh'] = new Uint8Array(
    fs.readFileSync(path.join(stateSrcDir, 'doctor.sh'))
  )
  execPaths.add('runtime/bin/doctor.sh')

  // state.sh → runtime/bin/state — drop the .sh suffix so LLM-facing command
  // is just `bash runtime/bin/state <subcommand>`.
  files['runtime/bin/state'] = new Uint8Array(
    fs.readFileSync(path.join(stateSrcDir, 'state.sh'))
  )
  execPaths.add('runtime/bin/state')

  // All .ts files — direct copy, no transpile. bun executes .ts natively,
  // so the archive ships TypeScript as-is. This is the same code path that
  // Soulkiller's unit tests import.
  const tsFiles = fs
    .readdirSync(stateSrcDir)
    .filter((f) => f.endsWith('.ts'))
    .sort()
  if (tsFiles.length === 0) {
    throw new Error(
      `injectRuntimeFiles: no .ts files found in ${stateSrcDir}. ` +
        `runtime lib is required for skill functionality.`
    )
  }
  for (const ts of tsFiles) {
    files[`runtime/lib/${ts}`] = new Uint8Array(
      fs.readFileSync(path.join(stateSrcDir, ts))
    )
  }

  return execPaths
}
