import { describe, it, expect } from 'vitest'
import { renderCatalogBlock, injectIntoReadme } from '../../../scripts/build-skill-catalog.js'

// NOTE: the script itself shells into examples/skills/*.skill via readFileSync
// in collectRows(); that path is covered by the integration run
// (`bun scripts/build-skill-catalog.ts`) during Phase B roll-out and by the
// CI verify-skill-catalog job. This suite pins the pure formatting /
// injection helpers.

describe('renderCatalogBlock (skill-catalog-autogen)', () => {
  it('emits header + separator + one row per skill', () => {
    const block = renderCatalogBlock([
      { slug: 'fate-zero', world: 'Fate/Zero', summary: '圣杯战争', archive: 'fz.skill' },
    ])
    expect(block).toContain('| slug | 世界 | 说明 |')
    expect(block).toContain('|------|------|------|')
    expect(block).toContain('| `fate-zero` | Fate/Zero | 圣杯战争 |')
  })

  it('escapes pipe characters inside cells', () => {
    const block = renderCatalogBlock([
      { slug: 'ab', world: 'Weird|World', summary: 'has | pipe', archive: 'x.skill' },
    ])
    expect(block).toContain('Weird\\|World')
    expect(block).toContain('has \\| pipe')
  })

  it('includes the autogen notice comment', () => {
    const block = renderCatalogBlock([])
    expect(block).toMatch(/auto-generated by scripts\/build-skill-catalog\.ts/)
  })
})

describe('injectIntoReadme (skill-catalog-autogen)', () => {
  const START = '<!-- SKILLS:START -->'
  const END = '<!-- SKILLS:END -->'

  it('replaces the content between markers and leaves surrounding text untouched', () => {
    const readme = `# Title\n\n${START}\nstale content\n${END}\n\nFooter\n`
    const catalog = 'fresh catalog'
    const result = injectIntoReadme(readme, catalog)
    expect(result).toBe(`# Title\n\n${START}\n${catalog}\n${END}\n\nFooter\n`)
  })

  it('is idempotent when called with the same catalog body', () => {
    const original = `before\n${START}\n\nfirst-call\n\n${END}\nafter`
    const once = injectIntoReadme(original, 'first-call\n')
    const twice = injectIntoReadme(once, 'first-call\n')
    expect(twice).toBe(once)
  })

  it('exits when START marker is missing', () => {
    const readme = `no markers ${END} here`
    const exitSpy = (process.exit as unknown as { mockImpl?: typeof process.exit })
    let exitCode: number | undefined
    const origExit = process.exit
    const origWrite = process.stderr.write
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    process.exit = ((code?: number) => { exitCode = code; throw new Error('__exit__') }) as any
    process.stderr.write = (() => true) as unknown as typeof process.stderr.write
    try {
      expect(() => injectIntoReadme(readme, 'x')).toThrow('__exit__')
      expect(exitCode).toBe(1)
    } finally {
      process.exit = origExit
      process.stderr.write = origWrite
      // silence unused
      void exitSpy
    }
  })

  it('exits when END marker appears before START', () => {
    const readme = `${END}\nfoo\n${START}`
    let exitCode: number | undefined
    const origExit = process.exit
    const origWrite = process.stderr.write
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    process.exit = ((code?: number) => { exitCode = code; throw new Error('__exit__') }) as any
    process.stderr.write = (() => true) as unknown as typeof process.stderr.write
    try {
      expect(() => injectIntoReadme(readme, 'x')).toThrow('__exit__')
      expect(exitCode).toBe(1)
    } finally {
      process.exit = origExit
      process.stderr.write = origWrite
    }
  })
})
