// Auto-generated by build.ts — do not edit
// This stub exists for development. The real content is generated during `bun run build:release`.
export const files: Record<string, { content: string; mime: string }> = {}
