#!/usr/bin/env bun
/**
 * skill-catalog-autogen: scan examples/skills/*.skill, read each archive's
 * soulkiller.json + SKILL.md frontmatter, and render the README catalog
 * table between the <!-- SKILLS:START --> / <!-- SKILLS:END --> markers.
 *
 * Modes:
 *   default — write README in place (idempotent)
 *   --check — dry-run; exit 1 when README would change (CI gate)
 *
 * Field resolution per row (three-level fallback):
 *   slug    : soulkiller.json.world_slug → soulkiller.json.skill_id
 *   world   : soulkiller.json.world_name → "—"
 *   summary : soulkiller.json.summary → SKILL.md frontmatter description → basename
 *
 * Fallbacks print a stderr warning but do not fail the script. Duplicate
 * world_slug across two archives DOES fail (exit 1) — ambiguous row identity.
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { basename, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { unzipSync, strFromU8 } from 'fflate'

// `import.meta.dir` is Bun-only; vitest evaluates this file with Node-style
// semantics, so derive the script directory via fileURLToPath instead.
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(SCRIPT_DIR, '..')
const SKILLS_DIR = resolve(ROOT, 'examples', 'skills')
const README_PATH = resolve(ROOT, 'README.md')

const START_MARKER = '<!-- SKILLS:START -->'
const END_MARKER = '<!-- SKILLS:END -->'
const AUTOGEN_NOTE = '<!-- This section is auto-generated by scripts/build-skill-catalog.ts — do not edit manually. -->'

interface SkillRow {
  slug: string
  world: string
  summary: string
  /** For error messages / warnings. */
  archive: string
}

function warn(msg: string): void {
  process.stderr.write(`[build-skill-catalog] WARN ${msg}\n`)
}

function die(msg: string): never {
  process.stderr.write(`[build-skill-catalog] ERROR ${msg}\n`)
  process.exit(1)
}

/** Extract a string field from a one-line frontmatter entry like
 *  `description: fz — 在Fate Zero中的…` (unquoted). Returns '' if not found. */
function parseFrontmatterString(frontmatter: string, key: string): string {
  const re = new RegExp(`^${key}:\\s*(.+?)\\s*$`, 'm')
  const m = frontmatter.match(re)
  if (!m) return ''
  let val = m[1]!.trim()
  // Strip surrounding quotes if present
  if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
    val = val.slice(1, -1)
  }
  return val
}

function readSkillMdDescription(entries: Record<string, Uint8Array>, wrapperName: string): string {
  const skillMd = entries[`${wrapperName}/SKILL.md`]
  if (!skillMd) return ''
  const content = strFromU8(skillMd)
  // Take the first frontmatter block (between the two `---` fences)
  const match = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n/)
  if (!match) return ''
  return parseFrontmatterString(match[1]!, 'description')
}

function readSkillRow(archivePath: string): SkillRow {
  const archiveName = basename(archivePath)
  const buf = new Uint8Array(readFileSync(archivePath))
  const entries = unzipSync(buf)

  // Detect wrapper dir name (all entries share the same top-level segment).
  let wrapperName = ''
  for (const entryPath of Object.keys(entries)) {
    const top = entryPath.split('/')[0] ?? ''
    if (wrapperName === '') wrapperName = top
    else if (top !== wrapperName) {
      die(`${archiveName}: archive has multiple top-level dirs (${wrapperName} vs ${top})`)
    }
  }
  if (wrapperName === '') die(`${archiveName}: archive is empty`)

  const manifestKey = `${wrapperName}/soulkiller.json`
  const manifestBytes = entries[manifestKey]
  if (!manifestBytes) {
    die(`${archiveName}: missing soulkiller.json at ${manifestKey}`)
  }
  let manifest: Record<string, unknown>
  try {
    manifest = JSON.parse(strFromU8(manifestBytes))
  } catch (err) {
    die(`${archiveName}: invalid soulkiller.json — ${err instanceof Error ? err.message : err}`)
  }

  const skillId = typeof manifest.skill_id === 'string' ? manifest.skill_id : ''
  const worldSlug = typeof manifest.world_slug === 'string' && manifest.world_slug.length > 0
    ? manifest.world_slug
    : null
  const worldName = typeof manifest.world_name === 'string' && manifest.world_name.length > 0
    ? manifest.world_name
    : null
  const summaryField = typeof manifest.summary === 'string' && manifest.summary.length > 0
    ? manifest.summary
    : null

  let slug = worldSlug ?? skillId
  if (!worldSlug) {
    warn(`${archiveName}: world_slug missing — falling back to skill_id "${skillId}"`)
  }
  if (!slug) {
    die(`${archiveName}: neither world_slug nor skill_id is set`)
  }

  let world = worldName ?? '—'
  if (!worldName) {
    warn(`${archiveName}: world_name missing — rendering as "—"`)
  }

  let summary: string
  if (summaryField) {
    summary = summaryField
  } else {
    const desc = readSkillMdDescription(entries, wrapperName)
    if (desc) {
      summary = desc
      warn(`${archiveName}: summary missing — falling back to SKILL.md description`)
    } else {
      summary = wrapperName
      warn(`${archiveName}: summary and SKILL.md description both missing — using archive basename`)
    }
  }

  return { slug, world, summary, archive: archiveName }
}

function collectRows(): SkillRow[] {
  const files = readdirSync(SKILLS_DIR)
    .filter((f) => f.endsWith('.skill'))
    .sort()
  if (files.length === 0) {
    die(`no .skill archives found in ${SKILLS_DIR}`)
  }

  const rows: SkillRow[] = []
  for (const f of files) {
    rows.push(readSkillRow(resolve(SKILLS_DIR, f)))
  }

  // Duplicate slug check — ambiguous row identity is a hard error.
  const bySlug = new Map<string, SkillRow>()
  for (const row of rows) {
    const existing = bySlug.get(row.slug)
    if (existing) {
      die(`duplicate slug "${row.slug}" — produced by both ${existing.archive} and ${row.archive}`)
    }
    bySlug.set(row.slug, row)
  }

  rows.sort((a, b) => a.slug.localeCompare(b.slug))
  return rows
}

/** Markdown tables render `|` as a column boundary — escape it inside cells. */
function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|')
}

export function renderCatalogBlock(rows: SkillRow[]): string {
  const header = '| slug | 世界 | 说明 |'
  const sep = '|------|------|------|'
  const body = rows
    .map((r) => `| \`${escapeCell(r.slug)}\` | ${escapeCell(r.world)} | ${escapeCell(r.summary)} |`)
    .join('\n')
  return `${AUTOGEN_NOTE}\n\n${header}\n${sep}\n${body}`
}

export function injectIntoReadme(readme: string, catalogBody: string): string {
  const startIdx = readme.indexOf(START_MARKER)
  const endIdx = readme.indexOf(END_MARKER)
  if (startIdx === -1 || endIdx === -1) {
    die(
      `README.md missing catalog placeholders. Insert the following pair into the "可装列表" section:\n\n${START_MARKER}\n${END_MARKER}\n`,
    )
  }
  if (endIdx < startIdx) {
    die(`${END_MARKER} appears before ${START_MARKER} — placeholders are misordered`)
  }
  const before = readme.slice(0, startIdx + START_MARKER.length)
  const after = readme.slice(endIdx)
  return `${before}\n${catalogBody}\n${after}`
}

/** Minimal unified-diff-lite for --check mode error output. Not byte-accurate,
 *  just enough to show the author which lines differ. */
function summarizeDiff(expected: string, actual: string): string {
  const expLines = expected.split('\n')
  const actLines = actual.split('\n')
  const max = Math.max(expLines.length, actLines.length)
  const out: string[] = []
  for (let i = 0; i < max; i++) {
    if (expLines[i] !== actLines[i]) {
      out.push(`  L${i + 1}:`)
      if (actLines[i] !== undefined) out.push(`    - ${actLines[i]}`)
      if (expLines[i] !== undefined) out.push(`    + ${expLines[i]}`)
    }
  }
  return out.slice(0, 40).join('\n')
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes('--check')

  const rows = collectRows()
  const catalogBody = renderCatalogBlock(rows)
  const current = readFileSync(README_PATH, 'utf8')
  const expected = injectIntoReadme(current, catalogBody)

  if (current === expected) {
    process.stdout.write(`[build-skill-catalog] README already up-to-date (${rows.length} skills)\n`)
    return
  }

  if (checkMode) {
    process.stderr.write('[build-skill-catalog] README is stale. Run `bun scripts/build-skill-catalog.ts` to update.\n')
    process.stderr.write('--- differing lines ---\n')
    process.stderr.write(summarizeDiff(expected, current) + '\n')
    process.exit(1)
  }

  writeFileSync(README_PATH, expected)
  process.stdout.write(`[build-skill-catalog] README updated with ${rows.length} skills\n`)
}

if (import.meta.main) {
  main().catch((err) => {
    process.stderr.write(`[build-skill-catalog] FATAL ${err?.stack ?? err}\n`)
    process.exit(1)
  })
}
