#!/usr/bin/env bun
/**
 * Generate `src/export/state/manifest.ts` — the bundler-visible list of
 * state CLI source files that must be embedded into the compiled soulkiller
 * binary (bun build --compile virtual FS).
 *
 * Background (runtime-manifest-bundling change):
 *   packager.ts used to `fs.readdirSync` state/*.ts at runtime, which works
 *   in dev (`bun src/index.tsx`) but breaks in the compiled binary because
 *   Bun's bundler can only see statically-reachable imports. This script
 *   generates a manifest with explicit `import … with { type: 'text' }`
 *   statements so every state file becomes part of the bundle.
 *
 * Output is committed. CI verifies committed manifest matches the state/
 * directory (verify-state-manifest job). Dev / test / build entry scripts
 * run this first so the manifest is always fresh.
 *
 * Idempotent: if the computed content matches the committed file byte-for-
 * byte, the file is NOT rewritten (mtime preserved).
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const STATE_DIR = resolve(__dirname, '..', 'src', 'export', 'state')
const MANIFEST_PATH = join(STATE_DIR, 'manifest.ts')

// Exclusions: the manifest itself, test/spec files, hidden files.
function shouldInclude(name: string): boolean {
  if (!name.endsWith('.ts')) return false
  if (name === 'manifest.ts') return false
  if (name.endsWith('.test.ts') || name.endsWith('.spec.ts')) return false
  if (name.startsWith('.')) return false
  return true
}

/**
 * `mini-yaml.ts` → `miniYaml` / `apply.ts` → `apply` / `script-builder.ts` → `scriptBuilder`
 * Kebab-case filename → camelCase identifier. Stable and reversible for valid identifiers.
 */
function toCamelCase(filename: string): string {
  const base = filename.replace(/\.ts$/, '')
  return base.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())
}

function buildManifest(files: string[], stateDir: string): string {
  const sorted = [...files].sort()
  // Inline every state/*.ts file as a JSON-stringified string literal.
  // Alternative approaches (with { type: 'text' }, Bun loaders) don't apply
  // cleanly to .ts extensions — bun treats them as TS modules regardless.
  // Inlining keeps the manifest self-contained and bundler-visible without
  // custom loaders, at the cost of a larger (but purely mechanical) file.
  const entries = sorted
    .map((f) => {
      const content = readFileSync(join(stateDir, f), 'utf8')
      return `  ${JSON.stringify(f)}: ${JSON.stringify(content)},`
    })
    .join('\n')

  return `/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Regenerated by \`bun scripts/gen-state-manifest.ts\` on every dev / test /
 * build. Committed so the compiled binary (\`bun build --compile\`) has the
 * full contents of every state/*.ts embedded — previous fs.readdirSync
 * approach broke in /$bunfs/root/.
 *
 * Source: src/export/state/*.ts (excluding manifest.ts itself).
 * See runtime-manifest-bundling change for background.
 */

export const RUNTIME_FILES: Record<string, string> = {
${entries}
}
`
}

function main(): number {
  if (!existsSync(STATE_DIR)) {
    console.error(`✗ state dir not found: ${STATE_DIR}`)
    return 1
  }

  const files = readdirSync(STATE_DIR).filter(shouldInclude)
  if (files.length === 0) {
    console.error(`✗ no .ts files found in ${STATE_DIR}`)
    return 1
  }

  const next = buildManifest(files, STATE_DIR)
  const current = existsSync(MANIFEST_PATH) ? readFileSync(MANIFEST_PATH, 'utf8') : ''

  if (next === current) {
    // Idempotent: no write, no mtime change
    return 0
  }

  writeFileSync(MANIFEST_PATH, next)
  console.log(`✓ ${MANIFEST_PATH} updated (${files.length} state files)`)
  return 0
}

if (import.meta.main) process.exit(main())

export { buildManifest, shouldInclude, toCamelCase }
