use_default_settings: true

server:
  secret_key: "soulkiller-searxng-dev"
  bind_address: "0.0.0.0"
  port: 8080

ui:
  default_locale: "zh-Hans-CN"

search:
  formats:
    - html
    - json
  default_lang: "zh-CN"

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: bing
    engine: bing
    shortcut: b
    disabled: false

  - name: reddit
    engine: reddit
    shortcut: r
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: wikidata
    engine: wikidata
    shortcut: wd
    disabled: false
